
function getUserToken() {
	//return "test_123456";
	return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzc0lkIjozLCJlbnYiOiJQUk9EIiwiZXhwaXJlZFRpbWUiOjE2MjUwNDA3OTksInJvbGUiOjAsInN0YWZmSWQiOjgsInN0b3JlSWQiOjN9.OtSjSZRmTtf_rao3C9nUdSBAkqUCwDFBqNnkINI-y0E";
}
